BZ1829779/curler: add drop-outliers parameter

diff --git a/BZ1829779/curler/analyze-curler-results b/BZ1829779/curler/analyze-curler-results
--- a/BZ1829779/curler/analyze-curler-results
+++ b/BZ1829779/curler/analyze-curler-results
@@ -19,7 +19,7 @@ declare -a colname=("DNS Lookup"
 		    "Content Transfer"
 		    "Completed")
 
-drop_dns_outliers=0
+drop_outliers=0
 highlight_filter=0.5
 highlight_outliers=0
 time_field="time_total"
@@ -41,9 +41,14 @@ while (( "$#" )); do
 		exit 1
 	    fi
 	    ;;
-	-d|--drop-dns-outliers)
-	    drop_dns_outliers=1
-	    shift
+	-d|--drop-outliers)
+	    if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
+		drop_outliers=$2
+		shift 2
+	    else
+		echo "Error: Argument for $1 is missing" >&2
+		exit 1
+	    fi
 	    ;;
 	-f|--time-field)
 	    if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
@@ -142,10 +147,10 @@ FROM results;
 EOF
 done
 
-if [[ $drop_dns_outliers == 1 ]]; then
-    count=$("$thisdir/sqlite3" "$db" "SELECT COUNT(*) FROM results WHERE time_namelookup >= 5.0")
-    echo "Dropping $count DNS outliers at >= 5.0s"
-    "$thisdir/sqlite3" "$db" "DELETE FROM results WHERE time_namelookup >= 5.0;"
+if [[ $drop_outliers > 0 ]]; then
+    count=$("$thisdir/sqlite3" "$db" "SELECT COUNT(*) FROM results WHERE time_total >= $drop_outliers")
+    echo "Dropping $count outliers >= $drop_outliers"
+    "$thisdir/sqlite3" "$db" "DELETE FROM results WHERE time_total >= $drop_outliers"
 fi
 
 if [[ $highlight_outliers == 0 ]]; then
