BZ1829779/curler: add limit flag

diff --git a/BZ1829779/curler/analyze-curler-results b/BZ1829779/curler/analyze-curler-results
--- a/BZ1829779/curler/analyze-curler-results
+++ b/BZ1829779/curler/analyze-curler-results
@@ -27,6 +27,7 @@ keep_db=0
 order_by_field="queryid";
 bins="total"
 summary=0
+limit=15
 
 PARAMS=""
 while (( "$#" )); do
@@ -66,6 +67,15 @@ while (( "$#" )); do
 	-k|--keep-db)
 	    keep_db=1
 	    shift
+	    ;;
+	-l|--limit)
+	    if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
+		limit=$2
+		shift 2
+	    else
+		echo "Error: Argument for $1 is missing" >&2
+		exit 1
+	    fi
 	    ;;
 	-o|--order-by)
 	    if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
@@ -184,28 +194,21 @@ echo
 "$thisdir/sqlite3" "$db" <<EOF
 .headers on
 .mode column
-SELECT results.*,
-COUNT(*) OVER (ROWS UNBOUNDED PRECEDING) AS count
-FROM results
-WHERE $time_field >= $highlight_filter
-ORDER BY $order_by_field
-EOF
-
-echo
-"$thisdir/sqlite3" "$db" <<EOF
-.headers on
-.mode column
-select queryid,
+select COUNT(*) OVER (ROWS UNBOUNDED PRECEDING) AS count,
+       queryid,
        timestamp,
        printf("%.6f", time_namelookup) AS "DNS Lookup",
        printf("%.6f", time_connect - time_namelookup) AS "TCP Connection",
        printf("%.6f", time_app_connect - time_connect) AS "TLS Handshake",
        printf("%.6f", time_starttransfer - time_pretransfer) AS "Server Processing",
        printf("%.6f", time_total - time_starttransfer) AS "Content Transfer",
+       port,
+       http_code,
        printf("%.6f", time_total) AS "TOTAL"
 from results
 WHERE $time_field >= $highlight_filter
 ORDER BY $order_by_field
+LIMIT $limit;
 EOF
 
 rm "$t"
