BZ1829779/curler: allow bin parameter

diff --git a/BZ1829779/curler/analyze-curler-results b/BZ1829779/curler/analyze-curler-results
--- a/BZ1829779/curler/analyze-curler-results
+++ b/BZ1829779/curler/analyze-curler-results
@@ -16,6 +16,15 @@ bins="total"
 PARAMS=""
 while (( "$#" )); do
     case "$1" in
+	-b|--bins)
+	    if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
+		bins=$2
+		shift 2
+	    else
+		echo "Error: Argument for $1 is missing" >&2
+		exit 1
+	    fi
+	    ;;
 	-d|--drop-dns-outliers)
 	    drop_dns_outliers=1
 	    shift
